services:
  coverart-proxy:
    build: .
    container_name: coverart-proxy
    restart: unless-stopped
    ports:
      - "7589:7589"
    volumes:
      - ./images:/app/images
    environment:
      - PORT=7589
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:7589/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s 